packages:
  - "contracts/*"
  - "packages/*"
  - "services/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bigint-buffer: true
  bufferutil: true
  keccak: true
  msgpackr-extract: true
  prisma: true
  react-native-screens: true
  secp256k1: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@expo/cli@54.0.25'
  - '@expo/json-file@10.0.16'
  - '@expo/metro-config@54.0.16'
  - '@expo/plist@0.4.9'
  - babel-preset-expo@54.0.11
  - expo-file-system@19.0.23
  - expo-font@14.0.12
  - expo-modules-autolinking@3.0.26
  - expo-server@1.0.7
  - expo@54.0.35
  - expo-router@6.0.24
