packages:
  - "contracts/*"
  - "packages/*"
  - "services/*"
  - "apps/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bigint-buffer: true
  bufferutil: true
  keccak: true
  msgpackr-extract: true
  prisma: true
  secp256k1: true
  utf-8-validate: true
